# Application
spring.application.name=course-enrollment-system

# Custom Server Port
server.port=8081

# Custom Property
training.system.name=Course Enrollment and Results System

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/course_enrollment_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Course Enrollment and Results System
info.app.description=COOP Backend Final Project